
run:
  runs-on:
    ubuntu-24.04: 2
    ubuntu-22.04: 1
  runtime:
    podman: 4
    sudo podman: 1
    docker rootless: 3
    docker: 2
  readonly:
    --read-only: 3
    "": null
  ca:
    "": 3
    --external-ca: 1
  volume:
    freeipa-data: 1
    "": null
  count: 13
  exclude:
    - arch: arm64
      runs-on: ubuntu-22.04
    # Workaround https://github.com/freeipa/freeipa-container/issues/660
    - runtime: sudo podman
      runs-on: ubuntu-22.04

test-upgrade:
  runs-on:
    ubuntu-24.04: 2
    ubuntu-22.04: 1
  runtime:
    podman: 3
    docker: 1
  volume:
    volume-image: 1
    volume: 1
    "": 1
  upgrade-to-from:
    fedora-rawhide:
      - fedora-42-4.12.2
    fedora-42:
      - fedora-42-4.12.2
      - fedora-41-4.12.2
    fedora-41:
      - fedora-41-4.12.2
      - fedora-40-4.11.1
    almalinux-9:
      - centos-9-stream-4.10.0
      - rocky-9-4.9.8
    rocky-9:
      - rocky-9-4.12.2
      - almalinux-9-4.10.0
    centos-9-stream:
      - centos-9-stream-4.12.2
    almalinux-8:
      - centos-8-4.8.7
    rocky-8:
      - centos-8-4.8.7
  count: 11
  exclude:
    - arch: arm64
      runs-on: ubuntu-22.04
    - volume: volume-image
      runtime: docker

k8s:
  runs-on:
    ubuntu-24.04: 2
    ubuntu-22.04: 1
  kubernetes:
    k3s: 1
    kubeadm init: 1
  runtime:
    cri-o: 1
    docker: 1
  count: 11
  exclude:
    - arch: arm64
      runs-on: ubuntu-22.04
    - kubernetes: kubeadm init
      runtime: docker

push:
  exclude:
    - os: centos-10-stream
    - os: fedora-42
      arch: arm64
    - os: fedora-41
      arch: arm64

